{% set name = "kaleido-core" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/plotly/Kaleido/releases/download/v{{ version }}/kaleido_minimal_linux_x64.zip  # [linux64]
  sha256: a78c227e62b5529d63201ce0d9c0892bf6e77b790cc8508e39085d2332598cb1  # [linux64]

  url: https://github.com/plotly/Kaleido/releases/download/v{{ version }}/kaleido_minimal_linux_arm64.zip  # [aarch64]
  sha256: cc74c62f6f38caa238d78426faf8ef680bf92eabb9829608454e8fe04628a703  # [aarch64]

  url: https://github.com/plotly/Kaleido/releases/download/v{{ version }}/kaleido_mac_x64.zip  # [osx]
  sha256: f4e482510400e2d26a6fb8049ae3b30198d0526df33da716a346abb7d1e56f1b  # [osx]

  url: https://github.com/plotly/Kaleido/releases/download/v{{ version }}/kaleido_mac_arm64.zip  # [arm64]
  sha256: 07328b495b33276a08b3edebb1c0618c2290d9c69eba9481a35ba90a5ebb731f  # [arm64]

  url: https://github.com/plotly/Kaleido/releases/download/v{{ version }}/kaleido_win_x64.zip  # [win]
  sha256: 684df0fb9f83997cee5db57517eeb170f362c0759c5f4fe043a719b097b5ff44  # [win]

build:
  number: 0
  ignore_run_exports:
    # Chromium loads sqlite dynamically
    - sqlite  # [linux]
  missing_dso_whitelist:
    - /usr/lib/*  # [osx or arm64]
    - /System/Library/Frameworks/*  # [osx or arm64]
  binary_relocation: False  # [osx or arm64]

requirements:
  build:
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux]
  host:
    - expat   # [linux]
    - nspr    # [linux]
    - nss     # [linux]
    - sqlite  # [linux]
  run:
    - expat   # [linux]
    - nspr    # [linux]
    - nss     # [linux]
    - sqlite  # [linux]
    - fontconfig         # [linux]
    - fonts-conda-forge  # [linux]
    - __osx >=10.11      # [osx]
    - mathjax =2.7

about:
  home: https://github.com/plotly/Kaleido
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - CREDITS.html
  summary: 'Fast static image export for web-based visualization libraries'
  description: |
    Kaleido is a cross-platform library for generating static images
    (e.g. png, svg, pdf, etc.) for web-based visualization libraries, with a
    particular focus on eliminating external dependencies.
  doc_url: https://github.com/plotly/Kaleido
  dev_url: https://github.com/plotly/Kaleido

extra:
  recipe-maintainers:
    - jonmmease
