{% set name = "kaleido-core" %}
{% set version = "0.2.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/plotly/Kaleido/releases/download/v{{ version }}/kaleido_minimal_linux_x64.zip  # [linux64]
  sha256: d2c6fd656bb5f4434d1cdd9c5d351e29adaebe030e75643dd7b30327dd171f08  # [linux64]

  url: https://github.com/plotly/Kaleido/releases/download/v{{ version }}/kaleido_minimal_linux_arm64.zip  # [aarch64]
  sha256: 59d360156b03fc8dc89a8d9e6458793093cc8f8d286a3b7c5a9bc184f8c6aee3  # [aarch64]

  url: https://github.com/plotly/Kaleido/releases/download/v{{ version }}/kaleido_mac_x64.zip  # [osx]
  sha256: 245ad5e02d277175276e61248862e0956f6de26e93f76bfa79fd33667f694a5d  # [osx]

  url: https://github.com/plotly/Kaleido/releases/download/v{{ version }}/kaleido_mac_arm64.zip  # [arm64]
  sha256: 6a80bcabd9bf2b07d4e76409b98c7d057b7cc27e6eddf88077cb46699719e477  # [arm64]

  url: https://github.com/plotly/Kaleido/releases/download/v{{ version }}/kaleido_win_x64.zip  # [win]
  sha256: 889b56109f1132071b3b00d2981edd35adc6a6c7b7125f9f2f12329d7feef950  # [win]

build:
  number: 0
  ignore_run_exports:
    # Chromium loads sqlite dynamically
    - sqlite  # [linux]
  missing_dso_whitelist:
    - /usr/lib/*  # [osx]
    - /System/Library/Frameworks/*  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux]
  host:
    - expat   # [linux]
    - nspr    # [linux]
    - nss     # [linux]
    - sqlite  # [linux]
  run:
    - expat   # [linux]
    - nspr    # [linux]
    - nss     # [linux]
    - sqlite  # [linux]
    - fontconfig         # [linux]
    - fonts-conda-forge  # [linux]
    - __osx >=10.11      # [osx]
    - mathjax =2.7

about:
  home: https://github.com/plotly/Kaleido
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - CREDITS.html
  summary: 'Fast static image export for web-based visualization libraries'
  description: |
    Kaleido is a cross-platform library for generating static images
    (e.g. png, svg, pdf, etc.) for web-based visualization libraries, with a
    particular focus on eliminating external dependencies.
  doc_url: https://github.com/plotly/Kaleido
  dev_url: https://github.com/plotly/Kaleido

extra:
  recipe-maintainers:
    - jonmmease
