{% set name = "kaleido-core" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/plotly/Kaleido/releases/download/v{{ version }}/kaleido_minimal_linux_x64.zip  # [linux]
  sha256: d1ad55b475c8bf622d961047186ce147a5ab1e45005550abce136c0cef3bac50  # [linux]

  url: https://github.com/plotly/Kaleido/releases/download/v{{ version }}/kaleido_mac.zip  # [osx]
  sha256: 4a583ee9363a9feed3ed6b7308ffeb1f11e8da57a978583bb7e9b4591dc55e38  # [osx]

  url: https://github.com/plotly/Kaleido/releases/download/v{{ version }}/kaleido_win_x64.zip  # [win]
  sha256: 58b57a973e660a4e7395e595a277492aa9008e0a25c3446656a52f7652b5f8a6  # [win]

build:
  number: 0
  ignore_run_exports:
    # Chromium loads sqlite dynamically
    - sqlite  # [linux]
  missing_dso_whitelist:
    - /usr/lib/*  # [osx]
    - /System/Library/Frameworks/*  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux]
  host:
    - expat   # [linux]
    - nspr    # [linux]
    - nss     # [linux]
    - sqlite  # [linux]
  run:
    - expat   # [linux]
    - nspr    # [linux]
    - nss     # [linux]
    - sqlite  # [linux]
    - fontconfig         # [linux]
    - fonts-conda-forge  # [linux]
    - __osx >=10.10      # [osx]

about:
  home: https://github.com/plotly/Kaleido
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - CREDITS.html
  summary: 'Fast static image export for web-based visualization libraries'
  description: |
    Kaleido is a cross-platform library for generating static images
    (e.g. png, svg, pdf, etc.) for web-based visualization libraries, with a
    particular focus on eliminating external dependencies.
  doc_url: https://github.com/plotly/Kaleido
  dev_url: https://github.com/plotly/Kaleido

extra:
  recipe-maintainers:
    - jonmmease
